G = gcc -g
O = -o
LIBS = -lglut -lGLU -lGL -lm -lpthread 
names = main openGL
parameters=parameters.txt

run:
	$(G)  main.c $(O) main $(LIBS)
	./main $(parameters) 

	
clean:
	rm plane-GL0 plane-GL0B plane-GL1 plane-GL1B collect-GL0 collect-GL1 collect-GL2 collect-GL0B collect-GL1B collect-GL2B split-GL0 split-GL1 split-GL2 split-GL0B split-GL1B  split-GL2B  distrib-GL0 distrib-GL1 distrib-GL2 collect-GL0BC collect-GL1BC collect-GL2BC collect-split0 collect-split1 collect-split2 split-GL0BC split-GL1BC split-GL2BC collect-GL0BCD collect-GL1BCD  collect-GL2BCD  distrib-GL0B distrib-GL1B  distrib-GL2B family-GL0 family-GL1 family-GL2 family-GL3 family-GL4 family-GL5 distrib-GL0BC distrib-GL1BC distrib-GL2BC distrib-GL0BCD distrib-GL1BCD distrib-GL2BCD split-GL3 split-GL3B split-GL3BC dstrb-split2 dstrb-split0 dstrb-split1 plane-parent0 plane-parent1 rm collector-parent0 collector-parent1 collector-parent2 distributer-parent0 distributer-parent1 distributer-parent2 family-parent0 family-parent1 family-parent2 family-parent3 family-parent4 family-parent5

	
	
