G = gcc -g
O = -o
LIBS = -lglut -lGLU -lGL -lm -lpthread 
parameters=parameters.txt

run:
	$(G)  main.c $(O) main $(LIBS)
	./main $(parameters) 
clean:
	rm line-parent0 line-parent1 botteled-parent1 pill-parent0 Lines-GL0-0 Lines-GL0-1 Lines-GL0-2 Lines-GL0-3 Lines-GL0-4 Lines-GL0-5 Lines-GL1-0 Lines-GL1-1 Lines-GL1-2 Lines-GL1  Lines-GL0 Lines-GL1-3 Lines-GL1-4 Lines-GL1-5 Lines-GL0-6 Lines-GL0-7 Lines-GL0-8 Lines-GL1-6 Lines-GL1-7 Lines-GL1-8 Lines-GL2 line-parent2 Lines-GL2-0 Lines-GL2-1 Lines-GL2-2 Lines-GL2-3 Lines-GL2-4 Lines-GL2-5 Lines-GL2-6 Lines-GL2-7 Lines-GL2-8 pill-parent2

	
	
